spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/department_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: department-service
  data:
    jdbc:
      dialect: mysql
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka